[book]
authors = ["mihneateodorstoica"]
language = "en"
src = "src"
title = "JovyKit"

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/MihneaTeodorStoica/jovykit"
edit-url-template = "https://github.com/MihneaTeodorStoica/jovykit/edit/main/docs/{path}"
